version: "3.9"

services:
  api:
    build:
      dockerfile: ./Dockerfile
    container_name: fastapi
    ports:
      - "8080:8080"
    volumes:
      - ./app:/code/app
    deploy:
      resources:
        limits:
          cpus: "${ES_CPUS}"
          memory: "${ES_MEMORY}"

