version: "3.9"

services:
  api:
    container_name: api
    build:
      dockerfile: app/Dockerfile
    env_file:
      - .env.dev
    ports:
      - "8989:8989"
#    user: root
    volumes:
      - ./app:/app
      - /var/run/docker.sock:/var/run/docker.sock
      - ./vector/chroma:/vector/chroma/
    command: python main.py --host 0.0.0.0 --port 8989 --env dev --reload

#  mlflow-deployment:
#    container_name: mlflow-deployment
#    build:
#      dockerfile: mlflow/deployment/Dockerfile
#    ports:
#      - "7001:7001"
#    networks:
#      - mlflow
#    environment:
#      OPENAI_API_KEY: ${OPENAI_API_KEY}
#    command: mlflow deployments start-server --config-path /mlflow_deployment/config.yaml --host 0.0.0.0 --port 7001

#  mlflow-tracking:
#    container_name: mlflow-tracking
#    build:
#      dockerfile: mlflow/tracking/Dockerfile
#    env_file:
#      - .env.dev
#    ports:
#      - "5001:5001"
#    networks:
#      - mlflow
#    links:
#      - mlflow-deployment
#    environment:
#      MLFLOW_DEPLOYMENTS_TARGET: ${MLFLOW_DEPLOYMENTS_TARGET}
#    command: mlflow server --host 0.0.0.0 --port 5001
#networks:
#  mlflow:

